In [1]:
import numpy as np
import pandas as pd
import yaml
import os

In [2]:
from nba_api.stats.endpoints.commonallplayers import CommonAllPlayers
from nba_api.stats.endpoints import leaguedashplayerstats

In [3]:
import pickle
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

In [4]:
all_players = CommonAllPlayers().common_all_players.get_data_frame()

In [5]:
player_stats = leaguedashplayerstats.LeagueDashPlayerStats(season_type_all_star='Playoffs').get_data_frames()[0]

In [6]:
player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Jalen Brunson"')

,PLAYER_NAME,PTS
67,Jalen Brunson,46


In [7]:
player_stats

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK
0,1630639,A.J. Lawson,A.J.,1610612742,DAL,23.0,1,0,1,0.0,...,65,1,1,107,137,86,149,20,3,149
1,1631260,AJ Green,AJ,1610612749,MIL,24.0,1,1,0,1.0,...,65,1,35,107,137,81,149,20,3,149
2,203932,Aaron Gordon,Aaron,1610612743,DEN,28.0,2,2,0,1.0,...,65,1,136,33,27,20,17,5,3,21
3,1630174,Aaron Nesmith,Aaron,1610612754,IND,24.0,1,0,1,0.0,...,26,1,62,41,91,72,90,20,3,90
4,1630598,Aaron Wiggins,Aaron,1610612760,OKC,25.0,1,1,0,1.0,...,65,1,1,81,93,98,107,20,3,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1629639,Tyler Herro,Tyler,1610612748,MIA,24.0,1,0,1,0.0,...,65,136,35,58,73,136,77,20,3,74
157,1630169,Tyrese Haliburton,Tyrese,1610612754,IND,24.0,1,0,1,0.0,...,26,1,1,81,81,95,59,20,3,62
158,1630178,Tyrese Maxey,Tyrese,1610612755,PHI,23.0,2,0,2,0.0,...,16,136,114,9,1,115,6,5,3,3
159,1628976,Wendell Carter Jr.,Wendell,1610612753,ORL,25.0,2,0,2,0.0,...,65,1,150,19,81,129,86,20,3,80


In [8]:
dp_fn = '/Users/joeseibert/Personal/git/nbapointsleague/drafted_players_2024.yml'

In [9]:
with open(dp_fn) as file:
    league = yaml.load(file, Loader=yaml.FullLoader)

In [10]:
for n in league:
    for p in league[n]:
        ps = player_stats[['PLAYER_NAME','PTS']].query(f'PLAYER_NAME=="{p}"')
        if len(ps) == 0:
            print(p)

Giannis Antetokounmpo


In [19]:
player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Luka Doncic"').to_numpy()

array([['Luka Doncic', 33]], dtype=object)

In [20]:
player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Luka Doncic"').to_numpy()[0]

array(['Luka Doncic', 33], dtype=object)

In [21]:
q,w = player_stats[['PLAYER_NAME','PTS']].query('PLAYER_NAME=="Kyrie Irving"').to_numpy()[0]

In [23]:
player_stats.query('TEAM_ABBREVIATION=="NYK"')

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK
14,202711,Bojan Bogdanovic,Bojan,1610612752,NYK,35.0,2,2,0,1.0,...,65,136,88,41,42,1,55,20,3,47
41,1628978,Donte DiVincenzo,Donte,1610612752,NYK,27.0,2,2,0,1.0,...,26,89,114,25,26,136,25,20,3,22
58,1628392,Isaiah Hartenstein,Isaiah,1610612752,NYK,25.0,2,2,0,1.0,...,1,1,150,58,38,136,16,20,3,22
67,1628973,Jalen Brunson,Jalen,1610612752,NYK,27.0,2,2,0,1.0,...,65,157,114,2,7,72,10,20,3,9
86,1628404,Josh Hart,Josh,1610612752,NYK,29.0,2,2,0,1.0,...,16,157,145,8,9,86,7,1,3,6
114,1630540,Miles McBride,Miles,1610612752,NYK,23.0,2,2,0,1.0,...,65,136,136,41,22,1,28,20,3,26
115,1629011,Mitchell Robinson,Mitchell,1610612752,NYK,26.0,2,2,0,1.0,...,5,1,114,58,81,7,34,20,3,42
127,1628384,OG Anunoby,OG,1610612752,NYK,26.0,2,2,0,1.0,...,26,1,62,41,36,98,47,20,3,50


In [24]:
pts = 0
gps = 0
for n in league:
    pts = 0
    gps = 0
    print(n)
    for p in league[n]:
        try:
            pname, pt, gp = player_stats[['PLAYER_NAME','PTS', 'GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
        except IndexError:
            pname = p
            pt = 0
            gp = 0
        print(pname, pt, gp)
        pts+=pt
        gps+=gp
    
    print(f'points: {pts}')
    print(f'gps: {gps}')
    print('\n')

Andrew
Jalen Brunson 46 2
Luka Doncic 33 1
Derrick White 20 1
Bradley Beal 15 1
Paolo Banchero 45 2
Myles Turner 17 1
Kentavious Caldwell-Pope 18 2
Josh Hart 43 2
points: 237
gps: 12


Jono
Jamal Murray 42 2
Anthony Edwards 33 1
Donte DiVincenzo 27 2
Chet Holmgren 15 1
OG Anunoby 21 2
Russell Westbrook 13 1
Nickeil Alexander-Walker 18 1
Brandon Ingram 12 1
points: 181
gps: 11


Connor
Jaylen Brown 17 1
Kristaps Porzingis 18 1
Jalen Williams 19 1
Karl-Anthony Towns 19 1
Tyrese Maxey 68 2
Franz Wagner 36 2
Naz Reid 12 1
Al Horford 10 1
points: 199
gps: 10


Joe
Shai Gilgeous-Alexander 28 1
Kyrie Irving 31 1
Tyrese Haliburton 9 1
Darius Garland 29 2
Aaron Gordon 26 2
LeBron James 53 2
James Harden 28 1
Payton Pritchard 8 1
points: 212
gps: 11


Julian
Jayson Tatum 23 1
Donovan Mitchell 53 2
Kevin Durant 31 1
Pascal Siakam 36 1
Michael Porter Jr. 41 2
Rudy Gobert 14 1
Anthony Davis 64 2
Tim Hardaway Jr. 6 1
points: 268
gps: 11


Sam
Nikola Jokic 59 2
Devin Booker 18 1
Paul George 22 1
Joel

In [13]:
# specifying which sheet to use
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']
spreadsheet_id = '1KHFofiupqYTIbuT8xL8atOuUjOOUM7mTbZzqOVtV2nw'

# taken from Google Sheets API instructions
creds = None
# The file token.pickle stores the user's access and refresh tokens, and is
# created automatically when the authorization flow completes for the first
# time.
if os.path.exists('token.pickle'):
    with open('token.pickle', 'rb') as token:
        creds = pickle.load(token)
# If there are no (valid) credentials available, let the user log in.
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'credentials.json', SCOPES)
        creds = flow.run_local_server(port=0)
    # Save the credentials for the next run
    with open('token.pickle', 'wb') as token:
        pickle.dump(creds, token)
        
service = build('sheets', 'v4', credentials=creds)
sheet = service.spreadsheets()

In [25]:
player_stats = leaguedashplayerstats.LeagueDashPlayerStats(season_type_all_star='Playoffs').get_data_frames()[0]

pts = []
gps = []
for n in league:
    pts = []
    gps = []
    pts_sheet_range = n+'!B2:B11'
    gps_sheet_range = n+'!C2:C11'
    for p in league[n]:
        try:
            pname, pt, gp = player_stats[['PLAYER_NAME','PTS','GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
            pname = p
            pts.append([str(pt)])
            gps.append([str(gp)])
        except IndexError:
            pname = p
            pt = 0
            gp = 0
            pts.append([str(pt)])
            gps.append([str(gp)])
        
    ptsvalues = pts
    gpsvalues = gps
    
    data = [
        {
            'range': pts_sheet_range,
            'values': ptsvalues
        },
        # Additional ranges to update ...
    ]
    body = {
        'valueInputOption': 'USER_ENTERED',
        'data': data
    }
    result = service.spreadsheets().values().batchUpdate(
        spreadsheetId=spreadsheet_id, body=body).execute()
    
    data = [
        {
            'range': gps_sheet_range,
            'values': gpsvalues
        },
        # Additional ranges to update ...
    ]
    body = {
        'valueInputOption': 'USER_ENTERED',
        'data': data
    }
    result = service.spreadsheets().values().batchUpdate(
        spreadsheetId=spreadsheet_id, body=body).execute()
        

In [23]:
drafted_players = np.array(list(league.values())).flatten()

In [24]:
udfa = player_stats[['PLAYER_NAME','PTS','GP']].sort_values('PTS',ascending=False).query(
            'PLAYER_NAME not in @drafted_players').iloc[:10].to_numpy()

In [25]:
pnames = []
pts = []
gps = []
pnames_sheet_range = 'Undrafted Players!A2:A11'
pts_sheet_range = 'Undrafted Players!B2:B11'
gps_sheet_range = 'Undrafted Players!C2:C11'

for p in udfa:
    pname, pt, gp = p
    pnames.append([str(pname)])
    pts.append([str(pt)])
    gps.append([str(gp)])
    
pnamesvalues = pnames
ptsvalues = pts
gpsvalues = gps
    
data = [
    {
        'range': pnames_sheet_range,
        'values': pnamesvalues
    },
    # Additional ranges to update ...
]
body = {
    'valueInputOption': 'USER_ENTERED',
    'data': data
}
result = service.spreadsheets().values().batchUpdate(
    spreadsheetId=spreadsheet_id, body=body).execute()
    
data = [
    {
        'range': pts_sheet_range,
        'values': ptsvalues
    },
    # Additional ranges to update ...
]
body = {
    'valueInputOption': 'USER_ENTERED',
    'data': data
}
result = service.spreadsheets().values().batchUpdate(
    spreadsheetId=spreadsheet_id, body=body).execute()

data = [
    {
        'range': gps_sheet_range,
        'values': gpsvalues
    },
    # Additional ranges to update ...
]
body = {
    'valueInputOption': 'USER_ENTERED',
    'data': data
}
result = service.spreadsheets().values().batchUpdate(
    spreadsheetId=spreadsheet_id, body=body).execute()



In [26]:
udfa

array([['Dorian Finney-Smith', 211, 18],
       ['Grant Williams', 207, 24],
       ['Tobias Harris', 203, 12],
       ['Max Strus', 196, 18],
       ['Reggie Bullock', 190, 18],
       ['Draymond Green', 176, 22],
       ['Brandon Ingram', 162, 6],
       ['Victor Oladipo', 159, 15],
       ['Maxi Kleber', 157, 18],
       ['Brandon Clarke', 148, 12]], dtype=object)

In [32]:
player_stats[['PLAYER_NAME','PTS']].sort_values('PTS', ascending=False).head(25).reset_index()

,index,PLAYER_NAME,PTS
0,104,Jayson Tatum,615
1,188,Stephen Curry,602
2,102,Jaylen Brown,554
3,139,Luka Doncic,475
4,107,Jimmy Butler,466
5,132,Klay Thompson,419
6,93,Jalen Brunson,388
7,75,Giannis Antetokounmpo,380
8,116,Jordan Poole,373
9,7,Andrew Wiggins,363


In [174]:
pts = []
gps = []
for n in league:
    pts = []
    gps = []
    pts_sheet_range = n+'!B2:B11'
    gps_sheet_range = n+'!C2:C11'
    for p in league[n]:
        try:
            pname, pt, gp = player_stats[['PLAYER_NAME','PTS','GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
            pname = p
            pts.append([str(pt)])
            gps.append([str(gp)])
        except IndexError:
            pname = p
            pt = 0
            gp = 0
            pts.append([str(pt)])
            gps.append([str(gp)])
        
    ptsvalues = pts
    gpsvalues = gps

In [176]:
pd.DataFrame(udfa, columns=['player_name', 'points', 'games_played'])

,player_name,points,games_played
0,Brandon Ingram,89,3
1,OG Anunoby,83,4
2,Tobias Harris,72,4
3,Nikola Vucevic,67,3
4,Brandon Clarke,61,4
5,Maxi Kleber,55,4
6,Bruce Brown,54,3
7,Bogdan Bogdanovic,53,3
8,Reggie Bullock,49,4
9,Dorian Finney-Smith,48,4


In [268]:
lg_pts = {}

for n in league:
    lg_pts.setdefault(n, [])
    for p in league[n]:
        try:
            pstats = player_stats[['PLAYER_NAME','PTS','GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
            lg_pts[n].append(tuple(pstats))
        except IndexError:
            pstats = (p, 0, 0)
            lg_pts[n].append(pstats)
    lg_pts[n] = np.array(lg_pts[n],
                         dtype=[('player_name', 'U50'), ('points', 'i4'), ('games_played', 'i4')])

In [270]:
lg_pts['Jono']

array([('Devin Booker', 56, 2), ('Desmond Bane', 93, 4),
       ('Jaylen Brown', 68, 3), ('Fred VanVleet', 55, 4),
       ('Brook Lopez', 54, 4), ('Cameron Johnson', 45, 4),
       ('Trae Young', 66, 4), ('Spencer Dinwiddie', 64, 4),
       ('Bones Hyland', 42, 4), ('Jonathan Kuminga', 10, 3)],
      dtype=[('player_name', '<U50'), ('points', '<i4'), ('games_played', '<i4')])

In [285]:
jonopts = pd.DataFrame(lg_pts['Jono'])
sampts = pd.DataFrame(lg_pts['Sam'])

# Making streamlit app

In [19]:
data = []
pts = 0
gps = 0
for n in league:
    pts = 0
    gps = 0
#     print(n)
    for p in league[n]:
        try:
            pname, pt, gp = player_stats[['PLAYER_NAME','PTS', 'GP']].query(f'PLAYER_NAME=="{p}"').to_numpy()[0]
        except IndexError:
            pname = p
            pt = 0
            gp = 0
#         print(pname, pt, gp)
        pts+=pt
        gps+=gp
    
    data.append(np.array([pts,gps,pts/gps]))
#     print(f'points: {pts}')
#     print(f'gps: {gps}')
#     print('\n')
data = np.array(data)

In [18]:
data

[array([237.  ,  12.  ,  19.75]),
 array([181.        ,  11.        ,  16.45454545]),
 array([199. ,  10. ,  19.9]),
 array([212.        ,  11.        ,  19.27272727]),
 array([268.        ,  11.        ,  24.36363636]),
 array([205.        ,   9.        ,  22.77777778])]

In [12]:
cols = np.array(['Points', 'Games Played', 'PPG'])

In [14]:
team_key = np.array([n for n in league])

In [20]:
df = pd.DataFrame(data=data,columns=cols,index=team_key)

In [21]:
df

,Points,Games Played,PPG
Andrew,237.0,12.0,19.750000
Jono,181.0,11.0,16.454545
Connor,199.0,10.0,19.900000
Joe,212.0,11.0,19.272727
Julian,268.0,11.0,24.363636
Sam,205.0,9.0,22.777778


In [22]:
df.to_csv('/Users/joeseibert/Personal/git/nbapointsleague/pointsleague_2024.csv')

In [23]:
df = pd.read_csv('/Users/joeseibert/Personal/git/nbapointsleague/pointsleague_2024.csv',index_col=0)

In [24]:
df

,Points,Games Played,PPG
Andrew,237.0,12.0,19.750000
Jono,181.0,11.0,16.454545
Connor,199.0,10.0,19.900000
Joe,212.0,11.0,19.272727
Julian,268.0,11.0,24.363636
Sam,205.0,9.0,22.777778


In [26]:
df.sort_values('Points',ascending=False)

,Points,Games Played,PPG
Julian,268.0,11.0,24.363636
Andrew,237.0,12.0,19.750000
Joe,212.0,11.0,19.272727
Sam,205.0,9.0,22.777778
Connor,199.0,10.0,19.900000
Jono,181.0,11.0,16.454545
